### ISSUE TITLE
In-tree volumes are populated

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/lib-volume-populator#41]
Kubernetes complains that only PVCs that refer to a CSI StorageClass can be populated, but hello-world populator will populate volumes for in-tree volume plugins anyway.

1. Create StorageClass referring to an in-tree volume plugin:
    ```yaml
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: thin
    parameters:
      diskformat: thin
    provisioner: kubernetes.io/vsphere-volume
    ```
    (vSphere is not yet migrated to CSI in this cluster!)
2. Create a PVC that refers to it + uses a data source:
    ```yaml
    kind: PersistentVolumeClaim
    metadata:
      name: mypvc-new
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
      dataSourceRef:
        apiGroup: hello.example.com
        kind: Hello
        name: example-hello
      volumeMode: Filesystem
    ```

3. Kubernetes PV controller warns that data sources are not supported, but the volume is Bound + populated:
```
kubectl describe pvc
...
Status:        Bound
...
  Warning  ProvisioningFailed  4m16s  persistentvolume-controller  plugin "kubernetes.io/vsphere-volume" is not a CSI plugin. Only CSI plugin can provision a claim with a datasource
```

So either CSI is required and the PVC should not get Bound or the event is wrong.
